In [46]:
import numpy as np
from math import pi, pow
from typing import Union, Tuple

In [7]:
pi

3.141592653589793

# Assignments

## Assignment 1

Create 3 Numpy arrays from the following three lists:

* [20, 56]
* [11, 78]
* [43, 65]

In [9]:
# create the lists
list_1 = [20, 56]
list_2 = [11, 78]
list_3 = [43, 65]

# create the arrays
array_1 = np.array(list_1)
array_2 = np.array(list_2)
array_3 = np.array(list_3)

type(array_1)

numpy.ndarray

## Assignment 2

Combine the arrays to a single array called diameters

In [11]:
# combine the arrays
diameters = np.concatenate([array_1, array_2, array_3])
diameters

array([20, 56, 11, 78, 43, 65])

## Assignment 3

Define a function (calc_circle) that calculates the size of a circle: (diameter / 2) ^ 2 * pi

In [13]:
# define the function


def calc_circle(diameter: Union[int, float]) -> Union[int, float]:
    '''
    Function to calculate the size of a circle

    Parameters:

    * diameter : The diameter of the circle
    
    '''

    # calculate the radius
    radius = diameter / 2

    # calculate the size
    size = pow(radius, 2) * pi

    return size

In [14]:
# test the function
calc_circle(10)

78.53981633974483

## Assignment 4

Create a new array sizes_circle based on the calc_circle function applied to the diameters that will contain the sizes of the circle based on the diameters in the diameters array.

In [19]:
# a. define the empty array

sizes_circle = []

for diameter in diameters:
    size = calc_circle(diameter)
    sizes_circle.append(size)

# convert to an array
sizes_circle = np.array(sizes_circle)

sizes_circle

12421.071954130644

In [21]:
# b. list comprehension
sizes_circle = np.array([calc_circle(diameter) for diameter in diameters])
sizes_circle

array([ 314.15926536, 2463.00864041,   95.03317777, 4778.36242611,
       1452.20120412, 3318.30724035])

## Assignment 5

Filter the sizes_circle array for only values above the avarage value of the sizes_circle array.

In [22]:
# calculate the mean size
mean_size = sizes_circle.mean()
mean_size

2070.178659021774

In [31]:
# define your filter
sizes_circle[sizes_circle > mean_size]

array([2463.00864041, 4778.36242611, 3318.30724035])

## Assignment 6


Create a function that prints the following information from the sizes_circle array:

* The number of values,
* standard deviation,
* min and max values
* the unique values
* the number of unique values

In [38]:
# function to display information about the array

def show_info(array: np.array) -> None:
    '''
    Function to display information about an array

    Parameters:
    * array: The numpy array to display the information for
    
    '''

    # show the number of values
    number_of_values = len(array)

    # standard deviation of the array
    standard_deviation = array.std()

    # min value
    min_value = array.min()

    # max value
    max_value = array.max()

    # unique values
    unique_values = np.unique(array)

    # number of unique values
    number_unique_values = len(unique_values)

    # print the values
    description_list = ["Number", "Standard Deviation", "Min", "Max", \
                        "Unique", "Number of unique"]
    
    values_list = [number_of_values, standard_deviation, min_value, \
                   max_value, unique_values, number_unique_values]


    # convert to a dictionary
    description_dict = dict(zip(description_list, values_list))

    # iterate over the dictionary
    for key, value in description_dict.items():
        print(f"{key}: {value}")


In [39]:
show_info(sizes_circle)

Number: 6
Standard Deviation: 1653.9397199782222
Min: 95.03317777109125
Max: 4778.362426110075
Unique: [  95.03317777  314.15926536 1452.20120412 2463.00864041 3318.30724035
 4778.36242611]
Number of unique: 6


## Assignment 7

Create a function, split_odd_even that accepts a numpy array and returns the odd and even numbers in two seperate arrays.

In [47]:
# define the function
def odd_even(array:np.array) -> Tuple[np.array, np.array]:
    '''
    Function to split an array in two seperate arrays with even or odd numbers

    Parameters:

    * array: The array to split
    '''

    # check for the odd numbers
    odd_numbers = array[array % 2 == 1]

    # check for the even numbers
    even_numbers = array[array % 2 == 0]

    return odd_numbers, even_numbers



In [49]:
# apply the function
even_diameters, odd_diameters = odd_even(diameters)

In [50]:
even_diameters

array([11, 43, 65])

In [51]:
odd_diameters

array([20, 56, 78])