In [19]:
import numpy as np

In [20]:
numbers = [1,2,3,4,5] # Python list
numbers_array = np.array(numbers)  # create an array from the list

In [3]:
numbers_array

array([1, 2, 3, 4, 5])

In [4]:
type(numbers)

list

In [5]:
type(numbers_array)

numpy.ndarray

In [6]:
numbers + numbers

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [7]:
numbers_array + numbers_array

array([ 2,  4,  6,  8, 10])

In [8]:
numbers / numbers

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [9]:
numbers_array / numbers_array

array([1., 1., 1., 1., 1.])

In [10]:
numbers.append(6)

In [16]:
numbers_array.std()

1.4142135623730951

In [21]:
np.power(5, 2)

25